name: goreleaser

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Set up Go
        uses: actions/setup-go@v5
      - 
        name: Check for tags
        id: check-tags
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "none")
          echo "Latest tag: $TAG"
          echo "::set-output name=tag::$TAG"
      - 
        name: Run GoReleaser if tagged
        if: steps.check-tags.outputs.tag != 'none'
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Nothing tagged yet
        if: steps.check-tags.outputs.tag == 'none'
        run: echo "Nothing tagged yet."
